title: Summer School & Hackathon
description: Summer School & Hackathon 2025
baseurl: /
url: https://algolab.github.io/forgenom_summerschool2025/

permalink: pretty
# theme: jekyll-nagymaros
remote_theme: piazzai/jekyll-nagymaros@v3.3.1

home: /
copyright: FORGENOM II & PANGAIA
indexing: true

exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

sass:
  sourcemap: never
